# -*- coding: utf-8 -*-
"""ChatBot_With_Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u-nn5NxI23P4bLgwo5PoAPXaRYmrJDxa
"""

pip install nltk

import nltk

nltk.download()

from nltk.tokenize import sent_tokenize

from nltk.tokenize import word_tokenize

text = "My name is santosh and I live in Hyderabad."

nltk.download('punkt')

print(sent_tokenize(text))

print(word_tokenize(text))

from nltk.stem import WordNetLemmatizer

nltk.download('wordnet')

from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

print("rocks: " ,lemmatizer.lemmatize("rocks"))
print("corpora: " ,lemmatizer.lemmatize("corpora"))
print("better: " ,lemmatizer.lemmatize("better" , pos = "a"))

from nltk.stem import PorterStemmer

from nltk.tokenize import word_tokenize

ps = PorterStemmer()

word = ["likes", "liked", "likely", "liking", "program", "programs", "programer", "programming", "programers"]
for i in word:
  print(i ,":", ps.stem(i))

!pip install chatterbot

!pip install chatterbot_corpus

!pip install --upgrade chatterbot

!pip install --upgrade chatterbot_corpus

from chatterbot import ChatBot

from chatterbot.trainers import ListTrainer

your_bot = ChatBot(name = "PyBot", readonly = True , logic_adapters = ['chatterbot.logic.MathematicalEvaluation','chatterbot.logic.BestMatch'])

greetings = ['hi' , 'Hello' , 'How are you?' , 'Im fine thank you.']
greetings1 = ['Hi' , 'Hello' , 'How are you?' , 'Im fine thank you.']
greetings2 = ['Hi' , 'Hello' , 'How are you?' , 'Im fine thank you.']
greetings3 = ['Hi' , 'Hello' , 'How are you?' , 'Im fine thank you.']
greetings4 = ['Hi' , 'Hello' , 'How are you?' , 'Im fine thank you.']
greetings5 = ['Hi' , 'Hello' , 'How are you?' , 'Im fine thank you.']

greetings1

train_your_bot = ListTrainer(your_bot)

for item in (greetings,greetings1,greetings2,greetings3,greetings4,greetings5):
  train_your_bot.train(item)

print(your_bot.get_response("hi"))

print(your_bot.get_response("How are you?"))